server: 
  port: 8503

spring: 
  application:
    name: mytoken-service-sso
  datasource: 
    druid:
      url: jdbc:mysql://192.168.48.135:3306/mytoken-service-user?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

eureka: 
  instance: 
    instance-id: mytoken-service-sso-8503
    prefer-ip-address: true     
    
info:  
  app.name: mytoken-service-admin
  company.name: ""
  build.artifactId: $project.artifactId$
  build.version: $project.version$
