spring: 
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

mybatis:
  configuration:
    cache-enabled: true   #开启二级缓存
  type-aliases-package: com.dys.springcloud.common.domain
  mapper-locations: classpath:mapper/*.xml


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info