server:
  port: 9411

spring:
  application:
    name: mytoken-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: mytoken-zipkin-9411   
    prefer-ip-address: true           

info:  
  app.name: mytoken-zipkin
  company.name: ""
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false