server: 
  port: 8602

spring: 
  application:
    name: mytoken-api-posts
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.48.136:26379,192.168.48.136:26380,192.168.48.136:26381

eureka: 
  instance: 
    instance-id: mytoken-api-admin-8602
    prefer-ip-address: true          
info:  
  app.name: mytoken-api-posts
  company.name: ""
  build.artifactId: $project.artifactId$
  build.version: $project.version$
