server: 
  port: 8888

spring: 
  application: 
    name: mytoken-config
  boot: 
    admin: 
      client: 
        url: http://localhost:8084
  cloud: 
    config: 
      label: master
      server: 
        git: 
          uri: https://github.com/dys97/MyToken.git
          search-paths: mytoken-config-respo
  zipkin: 
    base-url: http://localhost:9411


eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: mytoken-config-8888   
    prefer-ip-address: true    

info:  
  app.name: mytoken-config
  company.name: ""
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoint:
    health:
      show-details: always
  endpoints: 
    web:
      exposure:
        include: health,info